steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
      - --cache=true
      - --dockerfile=Dockerfile-frontendcsv
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - $_SERVICE_NAME
      - --platform
      - managed
      - --region
      - europe-west1
      - --allow-unauthenticated
      - --image
      - gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
substitutions:
  _SERVICE_NAME: kindly-frontendcsv