FROM golang:1.16 as builder
WORKDIR /go/src/app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-s -w" -o /bin/server ./cmd/frontendcsv

FROM alpine:latest
RUN apk update && apk add ca-certificates
COPY --from=builder /bin/server /bin/server
COPY --from=builder /go/src/app/start-frontendcsv.sh /bin/start.sh
CMD ["/bin/start.sh"]